name: eval
device: cuda
gpus: [0]
vis_result: True
vis_hm: False
vis_traj: False
#best_model_name: best_model.pth.tar
#model_dir: 
model_path: .//checkpoint/2024-07-19_19-08-38/checkpoint_ep30.pth.tar
split: test
fp1_filename: # dummy
eval:
  score_threshold: 0.5
  dist_threshold: 10

