name: train
device: cuda
gpus: [0]
max_epochs: 20
#vis_result: False
#vis_hm: False
#vis_traj: False
model_path:
pretrained_model: /mnt/data/yuxuan/checkpoint/2024-06-17_16-12-28_train/checkpoint_ep10.pth.tar
#split: train
fp1_filename:
best_model_name: best_model.pth
test:
  run: False
  epoch_start: 10
  epoch_step: 5
  run_before_train: False
  run_after_train_with_best: False
inference_video:
  run: False
  epoch_start: 10
  epoch_step: 5
  run_before_train: False
  run_after_train_with_best: False
find_fp1_epochs: []
eval:
  score_threshold: 0.5
  dist_threshold: 4
