train: True
test: True
train_clip: False
test_clip: False
#inference_video: True
sampler:
        name: random
        train_batch_size: 8
        train_shuffle_batch: True
        train_drop_last: True
        test_batch_size: 8
        test_shuffle_batch: False
        test_drop_last: False
        inference_video_batch_size: 8
        inference_video_shuffle_batch: False
        inference_video_drop_last: False
train_num_workers: 12
test_num_workers: 12
inference_video_num_workers: 12
heatmap:
        name: binary_fixed_size_multi
        sigmas: [3.0]
        mags: [1.0]
        min_value: 0.6
