name: multiball_new_spilt
root_dir: /mnt/data/yuxuan/wasb_data/multiball_full_scene
frame_dirname: pic
csv_dirname: label
ext: '.jpg'
train:
  matches: [huilongguan_1_1_train,
huilongguan_1_2_train,
huilongguan_2_1_train,
huilongguan_2_2_train,
huilongguan_400w_20231220_2100-2130_1_train,
huilongguan_400w_20231221_2100-2130_train,
huilongguan_400w_20231223_2100-2130_train,
jiangnan_bas_001_train,
jiangnan_bas_002_train,
jiangnan_bas_003_train,
jiangnan_bas_004_train,
jiangnan_bas_005_train,
jiangnan_bas_006_train,
jiubao_bas_001_train,
jiubao_bas_003_train,
lingang_bas_001_train,
lingang_bas_002_train,
lingang_bas_003_train,
lingang_bas_004_train,
menggangwan_bas_001_train,
menggangwan_bas_002_train,
qiantang_bas_001_train,
qiantang_bas_002_train,
qiantang_bas_003_train,
qiantang_bas_004_train,
weile_bas_001_train,
weile_bas_002_train,
xinan_bas_001_train,
xinan_bas_002_train,
xiyu_bas_001_train,
xiyu_bas_002_train,
xiyu_bas_003_train,
xiyu_bas_004_train,
xt_bas_001_train,
xt_bas_002_train,
xt_bas_003_train,
xt_bas_004_train,
huilongguan_400w_20231225_2100-2130_train,
jiubao_bas_002_train,]

  num_clip_ratio: 1.0
  
test:
  matches: [huilongguan_1_1_val,
huilongguan_1_2_val,
huilongguan_2_1_val,
huilongguan_2_2_val,
huilongguan_400w_20231220_2100-2130_1_val,
huilongguan_400w_20231221_2100-2130_val,
huilongguan_400w_20231223_2100-2130_val,
huilongguan_400w_20231225_2100-2130_val,
jiangnan_bas_001_val,
jiangnan_bas_002_val,
jiangnan_bas_003_val,
jiangnan_bas_004_val,
jiangnan_bas_005_val,
jiangnan_bas_006_val,
jiubao_bas_001_val,
jiubao_bas_002_val,
jiubao_bas_003_val,
lingang_bas_001_val,
lingang_bas_002_val,
lingang_bas_003_val,
lingang_bas_004_val,
menggangwan_bas_001_val,
menggangwan_bas_002_val,
qiantang_bas_002_val,
qiantang_bas_003_val,
qiantang_bas_004_val,
weile_bas_001_val,
weile_bas_002_val,
xinan_bas_001_val,
xinan_bas_002_val,
xiyu_bas_001_val,
xiyu_bas_002_val,
xiyu_bas_003_val,
xiyu_bas_004_val,
xt_bas_001_val,
xt_bas_002_val,
xt_bas_003_val,
xt_bas_004_val,
qiantang_bas_001_val,
              ]
  num_clip_ratio: 1.0