train:
  color_jitter:
    p: 0.5
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0.1
  horizontal_flip:
    p: 0.0
  crop:
    max_rescale: 0.125
    p: 0.0
test:
  color_jitter:
    p: 0.
    brightness: 0.
    contrast: 0.
    saturation: 0.
    hue: 0.
  horizontal_flip:
    p: 0.
  crop:
    p: 0.
