train:
  color_jitter:
    p: 0.
    brightness: 0.
    contrast: 0.
    saturation: 0.
    hue: 0.
  horizontal_flip:
    p: 0.
  crop:
    p: 0.
    max_rescale: 0.125
test:
  color_jitter:
    p: 0.
    brightness: 0.
    contrast: 0.
    saturation: 0.
    hue: 0.
  horizontal_flip:
    p: 0.
  crop:
    p: 0.
    max_rescale: 0.125
